package Vistas;

import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import java.util.HashMap;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.paint.Color;
import static javafx.scene.paint.Color.LIGHTBLUE;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormMenuPrincipal extends javax.swing.JFrame {
    
    

//Moverse entre paneles

    public void Ocultar(String panel) {
        pnlinicio.setVisible(false);
      
        pnEvento.setVisible(false);
     
//        pnlnuevo.setVisible(false);
       
  //      pnLenguage.setVisible(false);
  
    //    pnFilm.setVisible(false);
       
//        pnStaff.setVisible(false);
      
      ///  pnActor.setVisible(false);
       
        
        switch (panel) {
            case "inicio":
                pnlinicio.setVisible(true);
                break;
            case "consultas":
//                pnlnuevo.setVisible(true);
                break;
            case "lenguaje":
               // pnLenguage.setVisible(true);
                break;
            case "Film":
////                pnFilm.setVisible(true);
                break;
            case "staff":
//                pnStaff.setVisible(true);
                break;
           
        }

    }
//Creación del frame

    public FormMenuPrincipal() {
     
        initComponents();
       // setExtendedState(MAXIMIZED_BOTH);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnVerE = new javax.swing.JButton();
        btnCat = new javax.swing.JButton();
        btnMis = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnCerrarS = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pnlinicio = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        gastronomia = new javax.swing.JButton();
        educacion = new javax.swing.JButton();
        cultura = new javax.swing.JButton();
        espectaculos = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        teatro = new javax.swing.JButton();
        cine = new javax.swing.JButton();
        musica = new javax.swing.JButton();
        social = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        religion = new javax.swing.JButton();
        taller = new javax.swing.JButton();
        infantil = new javax.swing.JButton();
        deportes = new javax.swing.JButton();
        jPanel53 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        pnEvento = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEventos = new javax.swing.JTable();
        pnREvento = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        crNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        crDes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        crDir = new javax.swing.JTextField();
        btnCE = new javax.swing.JButton();
        dateTimePicker = new com.github.lgooddatepicker.components.DateTimePicker();
        jLabel6 = new javax.swing.JLabel();
        comboCat = new javax.swing.JComboBox();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        pnEvento1 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        desc1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnCom = new javax.swing.JButton();
        btnRep = new javax.swing.JButton();
        btnCom1 = new javax.swing.JButton();
        btnCom2 = new javax.swing.JButton();
        hora1 = new javax.swing.JLabel();
        fecha1 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        pnComentarios = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnEnviarCo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaCom = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        mensaje = new javax.swing.JTextArea();
        pnReportes = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnEnviarRep = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaRep = new javax.swing.JTextArea();
        textCausa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        textDesc = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel37 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(244, 244, 244));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 250, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 10));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 250, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_location_120px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 200));

        jButton1.setBackground(new java.awt.Color(244, 244, 244));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Salir");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 240, 40));

        btnVerE.setBackground(new java.awt.Color(244, 244, 244));
        btnVerE.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVerE.setText("Ver Eventos");
        btnVerE.setActionCommand("btnVerE");
        btnVerE.setBorder(null);
        btnVerE.setContentAreaFilled(false);
        btnVerE.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVerE.setOpaque(true);
        btnVerE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEActionPerformed(evt);
            }
        });
        jPanel2.add(btnVerE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 40));

        btnCat.setBackground(new java.awt.Color(244, 244, 244));
        btnCat.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCat.setText("Categorías");
        btnCat.setActionCommand("btnCat");
        btnCat.setBorder(null);
        btnCat.setContentAreaFilled(false);
        btnCat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCat.setOpaque(true);
        btnCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatActionPerformed(evt);
            }
        });
        jPanel2.add(btnCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 250, 40));

        btnMis.setBackground(new java.awt.Color(244, 244, 244));
        btnMis.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnMis.setText("Mis Eventos");
        btnMis.setActionCommand("btnMis");
        btnMis.setBorder(null);
        btnMis.setContentAreaFilled(false);
        btnMis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMis.setOpaque(true);
        btnMis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisActionPerformed(evt);
            }
        });
        jPanel2.add(btnMis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 250, 40));

        btnCrear.setBackground(new java.awt.Color(244, 244, 244));
        btnCrear.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCrear.setText("Crear Evento");
        btnCrear.setActionCommand("btnCrear");
        btnCrear.setBorder(null);
        btnCrear.setContentAreaFilled(false);
        btnCrear.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCrear.setOpaque(true);
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel2.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 250, 40));

        btnCerrarS.setBackground(new java.awt.Color(244, 244, 244));
        btnCerrarS.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCerrarS.setText("Cerrar Sesión");
        btnCerrarS.setActionCommand("btnCerrarS");
        btnCerrarS.setBorder(null);
        btnCerrarS.setContentAreaFilled(false);
        btnCerrarS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrarS.setOpaque(true);
        jPanel2.add(btnCerrarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 240, 40));

        jPanel3.setBackground(new java.awt.Color(31, 174, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setBackground(new java.awt.Color(31, 174, 255));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Eventos");
        jLabel32.setOpaque(true);
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.CardLayout());

        pnlinicio.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(0, 111, 177));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gastronomia.setBackground(new java.awt.Color(255, 153, 0));
        gastronomia.setForeground(new java.awt.Color(255, 255, 255));
        gastronomia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_hamburger_50px.png"))); // NOI18N
        gastronomia.setText("Gastronomía");
        gastronomia.setToolTipText("");
        gastronomia.setActionCommand("gastronomia");
        gastronomia.setBorder(null);
        gastronomia.setContentAreaFilled(false);
        gastronomia.setOpaque(true);
        jPanel13.add(gastronomia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 110));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 180, 110));

        educacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_school_50px.png"))); // NOI18N
        educacion.setText("Educación");
        educacion.setActionCommand("educacion");
        educacion.setBackground(new java.awt.Color(204, 0, 0));
        educacion.setBorder(null);
        educacion.setContentAreaFilled(false);
        educacion.setForeground(new java.awt.Color(255, 255, 255));
        educacion.setOpaque(true);
        educacion.setToolTipText("");
        jPanel12.add(educacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 180, 110));

        cultura.setBackground(new java.awt.Color(102, 0, 102));
        cultura.setForeground(new java.awt.Color(255, 255, 255));
        cultura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_ballet_dancer_50px.png"))); // NOI18N
        cultura.setText("Cultura");
        cultura.setToolTipText("");
        cultura.setActionCommand("cultura");
        cultura.setBorder(null);
        cultura.setContentAreaFilled(false);
        cultura.setOpaque(true);
        jPanel12.add(cultura, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 180, 110));

        espectaculos.setBackground(new java.awt.Color(0, 102, 153));
        espectaculos.setForeground(new java.awt.Color(255, 255, 255));
        espectaculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_maracas_50px.png"))); // NOI18N
        espectaculos.setText("Espectaculos");
        espectaculos.setToolTipText("");
        espectaculos.setActionCommand("espectaculos");
        espectaculos.setBorder(null);
        espectaculos.setContentAreaFilled(false);
        espectaculos.setOpaque(true);
        jPanel12.add(espectaculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 110));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel11.add(jPanel12, gridBagConstraints);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setForeground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new java.awt.GridBagLayout());

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(59, 148, 109));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teatro.setBackground(new java.awt.Color(204, 0, 0));
        teatro.setForeground(new java.awt.Color(255, 255, 255));
        teatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_edvard_munch_50px.png"))); // NOI18N
        teatro.setText("Teatro");
        teatro.setToolTipText("");
        teatro.setActionCommand("teatro");
        teatro.setBorder(null);
        teatro.setContentAreaFilled(false);
        teatro.setOpaque(true);
        teatro.setRequestFocusEnabled(false);
        jPanel19.add(teatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 110));

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 180, 110));

        cine.setBackground(new java.awt.Color(0, 102, 153));
        cine.setForeground(new java.awt.Color(255, 255, 255));
        cine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_video_camera_50px.png"))); // NOI18N
        cine.setText("Cine");
        cine.setToolTipText("");
        cine.setActionCommand("cine");
        cine.setBorder(null);
        cine.setContentAreaFilled(false);
        cine.setOpaque(true);
        jPanel18.add(cine, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 180, 110));

        musica.setBackground(new java.awt.Color(102, 0, 102));
        musica.setForeground(new java.awt.Color(255, 255, 255));
        musica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_micro_50px.png"))); // NOI18N
        musica.setText("Música");
        musica.setToolTipText("");
        musica.setActionCommand("musica");
        musica.setBorder(null);
        musica.setContentAreaFilled(false);
        musica.setOpaque(true);
        jPanel18.add(musica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 110));

        social.setBackground(new java.awt.Color(255, 153, 0));
        social.setForeground(new java.awt.Color(255, 255, 255));
        social.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_crowd_50px.png"))); // NOI18N
        social.setText("Social");
        social.setToolTipText("");
        social.setActionCommand("social");
        social.setBorder(null);
        social.setContentAreaFilled(false);
        social.setOpaque(true);
        jPanel18.add(social, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 180, 110));

        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Cultura");
        jButton13.setToolTipText("");
        jButton13.setBorder(null);
        jPanel18.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 180, 110));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel17.add(jPanel18, gridBagConstraints);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 111, 177));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        religion.setBackground(new java.awt.Color(102, 0, 102));
        religion.setForeground(new java.awt.Color(255, 255, 255));
        religion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_trust_50px.png"))); // NOI18N
        religion.setText("Religión");
        religion.setToolTipText("");
        religion.setActionCommand("religion");
        religion.setBorder(null);
        religion.setContentAreaFilled(false);
        religion.setOpaque(true);
        jPanel6.add(religion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 110));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 180, 110));

        taller.setBackground(new java.awt.Color(0, 204, 51));
        taller.setForeground(new java.awt.Color(255, 255, 255));
        taller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_hammer_50px.png"))); // NOI18N
        taller.setText("Taller");
        taller.setToolTipText("");
        taller.setActionCommand("taller");
        taller.setBorder(null);
        taller.setContentAreaFilled(false);
        taller.setOpaque(true);
        taller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tallerActionPerformed(evt);
            }
        });
        jPanel5.add(taller, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 110));

        infantil.setBackground(new java.awt.Color(204, 0, 0));
        infantil.setForeground(new java.awt.Color(255, 255, 255));
        infantil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_short_curly_hair_girl_pencil_50px.png"))); // NOI18N
        infantil.setText("Infantil");
        infantil.setToolTipText("");
        infantil.setActionCommand("infantil");
        infantil.setBorder(null);
        infantil.setContentAreaFilled(false);
        infantil.setOpaque(true);
        jPanel5.add(infantil, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 180, 110));

        deportes.setBackground(new java.awt.Color(0, 204, 51));
        deportes.setForeground(new java.awt.Color(255, 255, 255));
        deportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_american_football_player_50px.png"))); // NOI18N
        deportes.setText("Deportes");
        deportes.setToolTipText("");
        deportes.setActionCommand("deportes");
        deportes.setBorder(null);
        deportes.setContentAreaFilled(false);
        deportes.setOpaque(true);
        deportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deportesActionPerformed(evt);
            }
        });
        jPanel5.add(deportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 180, 110));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel10.add(jPanel5, gridBagConstraints);

        jPanel53.setBackground(new java.awt.Color(255, 255, 255));
        jPanel53.setForeground(new java.awt.Color(255, 255, 255));
        jPanel53.setLayout(new java.awt.GridBagLayout());
        jPanel10.add(jPanel53, new java.awt.GridBagConstraints());

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setLayout(new java.awt.GridBagLayout());

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel23.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 260, 10));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tablero");
        jLabel3.setOpaque(true);
        jPanel23.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 40));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel24.add(jPanel23, gridBagConstraints);

        javax.swing.GroupLayout pnlinicioLayout = new javax.swing.GroupLayout(pnlinicio);
        pnlinicio.setLayout(pnlinicioLayout);
        pnlinicioLayout.setHorizontalGroup(
            pnlinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlinicioLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 1023, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlinicioLayout.setVerticalGroup(
            pnlinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlinicioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(369, Short.MAX_VALUE))
        );

        jPanel4.add(pnlinicio, "card2");

        pnEvento.setBackground(new java.awt.Color(255, 255, 255));

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setLayout(new java.awt.GridBagLayout());

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Eventos");
        jLabel33.setOpaque(true);

        jEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Evento", "Nombre", "Descripción", "Fecha", "Hora"
            }
        ));
        jEventos.setGridColor(new java.awt.Color(102, 153, 255));
        jEventos.setIntercellSpacing(new java.awt.Dimension(3, 3));
        jEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEventosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jEventos);

        javax.swing.GroupLayout pnEventoLayout = new javax.swing.GroupLayout(pnEvento);
        pnEvento.setLayout(pnEventoLayout);
        pnEventoLayout.setHorizontalGroup(
            pnEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEventoLayout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 641, Short.MAX_VALUE)
                .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
            .addGroup(pnEventoLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnEventoLayout.setVerticalGroup(
            pnEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEventoLayout.createSequentialGroup()
                .addGroup(pnEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnEventoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnEventoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(362, Short.MAX_VALUE))
        );

        jPanel4.add(pnEvento, "card3");

        pnREvento.setBackground(new java.awt.Color(255, 255, 255));

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setLayout(new java.awt.GridBagLayout());

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel27.add(jPanel28, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Nombre del Evento:");

        crNom.setBackground(new java.awt.Color(102, 153, 255));
        crNom.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        crNom.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Descripción:");

        crDes.setBackground(new java.awt.Color(102, 153, 255));
        crDes.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        crDes.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Fecha:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Dirección:");

        crDir.setBackground(new java.awt.Color(102, 153, 255));
        crDir.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        crDir.setForeground(new java.awt.Color(255, 255, 255));

        btnCE.setBackground(new java.awt.Color(31, 174, 255));
        btnCE.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCE.setForeground(new java.awt.Color(255, 255, 255));
        btnCE.setText("Crear ");
        btnCE.setActionCommand("btnCE");
        btnCE.setBorder(null);
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        dateTimePicker.setBackground(new java.awt.Color(31, 174, 255));
        dateTimePicker.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Categoría:");

        comboCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "Espectaculos", "Música", "Taller", "Social", "Religión", "Deportes", "Teatro", "Infantil", "Cultura", "Educación", "Gastronomía", "Cine" }));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Registrar Evento");
        jLabel34.setOpaque(true);

        javax.swing.GroupLayout pnREventoLayout = new javax.swing.GroupLayout(pnREvento);
        pnREvento.setLayout(pnREventoLayout);
        pnREventoLayout.setHorizontalGroup(
            pnREventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, 1801, Short.MAX_VALUE)
            .addGroup(pnREventoLayout.createSequentialGroup()
                .addGroup(pnREventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnREventoLayout.createSequentialGroup()
                        .addGroup(pnREventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnREventoLayout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addGroup(pnREventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnREventoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnREventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(crNom, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(crDes)
                            .addComponent(crDir))
                        .addGap(51, 51, 51)
                        .addGroup(pnREventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(pnREventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboCat, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnREventoLayout.createSequentialGroup()
                        .addGap(497, 497, 497)
                        .addGroup(pnREventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnREventoLayout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(jLabel34)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnREventoLayout.setVerticalGroup(
            pnREventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnREventoLayout.createSequentialGroup()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(pnREventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(dateTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crNom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnREventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnREventoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(pnREventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crDes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnREventoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnREventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboCat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)))
                .addGroup(pnREventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crDir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(423, 423, 423))
        );

        jPanel4.add(pnREvento, "card3");

        pnEvento1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setLayout(new java.awt.GridBagLayout());

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel29.add(jPanel30, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Nombre del Evento:");

        desc1.setBackground(new java.awt.Color(51, 153, 255));
        desc1.setForeground(new java.awt.Color(102, 153, 255));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Descripción:");

        nombre1.setBackground(new java.awt.Color(102, 153, 255));
        nombre1.setForeground(new java.awt.Color(102, 153, 255));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Fecha:");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Hora:");

        btnCom.setBackground(new java.awt.Color(31, 174, 255));
        btnCom.setText("Ver Comentarios");
        btnCom.setActionCommand("btnCom");
        btnCom.setBorder(null);
        btnCom.setContentAreaFilled(false);
        btnCom.setOpaque(true);

        btnRep.setBackground(new java.awt.Color(31, 174, 255));
        btnRep.setText("Reportar");
        btnRep.setActionCommand("btnRep");
        btnRep.setBorder(null);
        btnRep.setContentAreaFilled(false);
        btnRep.setOpaque(true);

        btnCom1.setBackground(new java.awt.Color(31, 174, 255));
        btnCom1.setText("Asistiré");
        btnCom1.setBorder(null);
        btnCom1.setContentAreaFilled(false);
        btnCom1.setOpaque(true);

        btnCom2.setBackground(new java.awt.Color(31, 174, 255));
        btnCom2.setText("Me interesa");
        btnCom2.setBorder(null);
        btnCom2.setContentAreaFilled(false);
        btnCom2.setOpaque(true);

        hora1.setBackground(new java.awt.Color(102, 153, 255));
        hora1.setForeground(new java.awt.Color(102, 153, 255));

        fecha1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Evento");
        jLabel35.setOpaque(true);

        javax.swing.GroupLayout pnEvento1Layout = new javax.swing.GroupLayout(pnEvento1);
        pnEvento1.setLayout(pnEvento1Layout);
        pnEvento1Layout.setHorizontalGroup(
            pnEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel29, javax.swing.GroupLayout.DEFAULT_SIZE, 1791, Short.MAX_VALUE)
            .addGroup(pnEvento1Layout.createSequentialGroup()
                .addGroup(pnEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnEvento1Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addGroup(pnEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnEvento1Layout.createSequentialGroup()
                                .addGap(383, 383, 383)
                                .addComponent(btnCom2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnEvento1Layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addGroup(pnEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnEvento1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(desc1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnEvento1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnEvento1Layout.createSequentialGroup()
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(hora1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(179, 179, 179))
                                .addGroup(pnEvento1Layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnCom1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCom, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnEvento1Layout.createSequentialGroup()
                        .addGap(682, 682, 682)
                        .addComponent(jLabel35)))
                .addContainerGap(718, Short.MAX_VALUE))
        );
        pnEvento1Layout.setVerticalGroup(
            pnEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEvento1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desc1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(fecha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(pnEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hora1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(pnEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCom1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCom2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnEvento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRep, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCom, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        jPanel4.add(pnEvento1, "card3");

        pnComentarios.setBackground(new java.awt.Color(255, 255, 255));

        jPanel31.setBackground(new java.awt.Color(255, 255, 255));
        jPanel31.setLayout(new java.awt.GridBagLayout());

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Comentarios");
        jLabel36.setOpaque(true);
        jPanel32.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 40));
        jPanel32.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 260, 10));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel31.add(jPanel32, gridBagConstraints);

        btnEnviarCo.setBackground(new java.awt.Color(31, 174, 255));
        btnEnviarCo.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarCo.setText("Enviar Comentario");
        btnEnviarCo.setActionCommand("btnEnviarCo");
        btnEnviarCo.setBorder(null);
        btnEnviarCo.setContentAreaFilled(false);
        btnEnviarCo.setOpaque(true);

        areaCom.setBackground(new java.awt.Color(102, 153, 255));
        areaCom.setColumns(20);
        areaCom.setRows(5);
        jScrollPane3.setViewportView(areaCom);

        mensaje.setBackground(new java.awt.Color(102, 153, 255));
        mensaje.setColumns(20);
        mensaje.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mensaje.setRows(5);
        jScrollPane4.setViewportView(mensaje);

        javax.swing.GroupLayout pnComentariosLayout = new javax.swing.GroupLayout(pnComentarios);
        pnComentarios.setLayout(pnComentariosLayout);
        pnComentariosLayout.setHorizontalGroup(
            pnComentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnComentariosLayout.createSequentialGroup()
                .addGroup(pnComentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnComentariosLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnComentariosLayout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnComentariosLayout.createSequentialGroup()
                        .addGap(484, 484, 484)
                        .addComponent(btnEnviarCo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnComentariosLayout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnComentariosLayout.setVerticalGroup(
            pnComentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnComentariosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnComentariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnComentariosLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnComentariosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnviarCo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        jPanel4.add(pnComentarios, "card3");

        pnReportes.setBackground(new java.awt.Color(255, 255, 255));

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setLayout(new java.awt.GridBagLayout());

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel33.add(jPanel34, gridBagConstraints);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setText("Nombre del Evento:");

        btnEnviarRep.setBackground(new java.awt.Color(31, 174, 255));
        btnEnviarRep.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarRep.setText("Enviar Reporte");
        btnEnviarRep.setActionCommand("btnEnviarRep");
        btnEnviarRep.setBorder(null);
        btnEnviarRep.setContentAreaFilled(false);
        btnEnviarRep.setOpaque(true);
        btnEnviarRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarRepActionPerformed(evt);
            }
        });

        areaRep.setEditable(false);
        areaRep.setBackground(new java.awt.Color(102, 153, 255));
        areaRep.setColumns(20);
        areaRep.setRows(5);
        jScrollPane2.setViewportView(areaRep);

        textCausa.setBackground(new java.awt.Color(102, 153, 255));
        textCausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCausaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Causa:");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Descripción:");

        textDesc.setBackground(new java.awt.Color(102, 153, 255));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Eventos");
        jLabel37.setOpaque(true);

        javax.swing.GroupLayout pnReportesLayout = new javax.swing.GroupLayout(pnReportes);
        pnReportes.setLayout(pnReportesLayout);
        pnReportesLayout.setHorizontalGroup(
            pnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnReportesLayout.createSequentialGroup()
                .addGroup(pnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnReportesLayout.createSequentialGroup()
                        .addGroup(pnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnReportesLayout.createSequentialGroup()
                                .addGap(386, 386, 386)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(482, 482, 482))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnReportesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(299, 299, 299)))
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnReportesLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(pnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnReportesLayout.createSequentialGroup()
                                .addGroup(pnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(pnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                                    .addComponent(textCausa)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnReportesLayout.createSequentialGroup()
                        .addGap(581, 581, 581)
                        .addComponent(jLabel37))
                    .addGroup(pnReportesLayout.createSequentialGroup()
                        .addGap(464, 464, 464)
                        .addComponent(btnEnviarRep, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(430, Short.MAX_VALUE))
        );
        pnReportesLayout.setVerticalGroup(
            pnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnReportesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnReportesLayout.createSequentialGroup()
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(pnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCausa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(pnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(textDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnEnviarRep, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jPanel4.add(pnReportes, "card3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCEActionPerformed

    private void tallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tallerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tallerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVerEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEActionPerformed
        btnVerE.setBackground(new java.awt.Color(31, 174, 255));
        btnVerE.setForeground(new java.awt.Color(255, 255, 255));

        btnCat.setBackground(new java.awt.Color(244, 244, 244));
        btnCat.setForeground(new java.awt.Color(11, 10, 9));

        btnCrear.setBackground(new java.awt.Color(244, 244, 244));
        btnCrear.setForeground(new java.awt.Color(11, 10, 9));

        btnMis.setBackground(new java.awt.Color(244, 244, 244));
        btnMis.setForeground(new java.awt.Color(11, 10, 9));

      
    }//GEN-LAST:event_btnVerEActionPerformed

    private void btnCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatActionPerformed
        btnCat.setBackground(new java.awt.Color(31, 174, 255));
        btnCat.setForeground(new java.awt.Color(255, 255, 255));
////
        btnVerE.setBackground(new java.awt.Color(244, 244, 244));
        btnVerE.setForeground(new java.awt.Color(11, 10, 9));

        btnCrear.setBackground(new java.awt.Color(244, 244, 244));
        btnCrear.setForeground(new java.awt.Color(11, 10, 9));

        btnMis.setBackground(new java.awt.Color(244, 244, 244));
        btnMis.setForeground(new java.awt.Color(11, 10, 9));
    }//GEN-LAST:event_btnCatActionPerformed

    private void btnMisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisActionPerformed
        btnMis.setBackground(new java.awt.Color(31, 174, 255));
        btnMis.setForeground(new java.awt.Color(255, 255, 255));
////
        btnCat.setBackground(new java.awt.Color(244, 244, 244));
        btnCat.setForeground(new java.awt.Color(11, 10, 9));

        btnCrear.setBackground(new java.awt.Color(244, 244, 244));
        btnCrear.setForeground(new java.awt.Color(11, 10, 9));

        btnVerE.setBackground(new java.awt.Color(244, 244, 244));
        btnVerE.setForeground(new java.awt.Color(11, 10, 9));
    }//GEN-LAST:event_btnMisActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        btnCrear.setBackground(new java.awt.Color(31, 174, 255));
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
////
        btnCat.setBackground(new java.awt.Color(244, 244, 244));
        btnCat.setForeground(new java.awt.Color(11, 10, 9));

        btnMis.setBackground(new java.awt.Color(244, 244, 244));
        btnMis.setForeground(new java.awt.Color(11, 10, 9));

        btnVerE.setBackground(new java.awt.Color(244, 244, 244));
        btnVerE.setForeground(new java.awt.Color(11, 10, 9));
    }//GEN-LAST:event_btnCrearActionPerformed

    private void textCausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCausaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCausaActionPerformed

    private void btnEnviarRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarRepActionPerformed

    private void deportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deportesActionPerformed

    private void jEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEventosMouseClicked
        
    }//GEN-LAST:event_jEventosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea areaCom;
    public javax.swing.JTextArea areaRep;
    public javax.swing.JButton btnCE;
    public javax.swing.JButton btnCat;
    public javax.swing.JButton btnCerrarS;
    public javax.swing.JButton btnCom;
    public javax.swing.JButton btnCom1;
    public javax.swing.JButton btnCom2;
    public javax.swing.JButton btnCrear;
    public javax.swing.JButton btnEnviarCo;
    public javax.swing.JButton btnEnviarRep;
    public javax.swing.JButton btnMis;
    public javax.swing.JButton btnRep;
    public javax.swing.JButton btnVerE;
    public javax.swing.JButton cine;
    public javax.swing.JComboBox comboCat;
    public javax.swing.JTextField crDes;
    public javax.swing.JTextField crDir;
    public javax.swing.JTextField crNom;
    public javax.swing.JButton cultura;
    public com.github.lgooddatepicker.components.DateTimePicker dateTimePicker;
    public javax.swing.JButton deportes;
    public javax.swing.JLabel desc1;
    public javax.swing.JButton educacion;
    public javax.swing.JButton espectaculos;
    public javax.swing.JLabel fecha1;
    public javax.swing.JButton gastronomia;
    public javax.swing.JLabel hora1;
    public javax.swing.JButton infantil;
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    public javax.swing.JTable jEventos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    public javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JTextArea mensaje;
    public javax.swing.JButton musica;
    public javax.swing.JLabel nombre1;
    public javax.swing.JPanel pnComentarios;
    public javax.swing.JPanel pnEvento;
    public javax.swing.JPanel pnEvento1;
    public javax.swing.JPanel pnREvento;
    public javax.swing.JPanel pnReportes;
    public javax.swing.JPanel pnlinicio;
    public javax.swing.JButton religion;
    public javax.swing.JButton social;
    public javax.swing.JButton taller;
    public javax.swing.JButton teatro;
    public javax.swing.JTextField textCausa;
    public javax.swing.JTextField textDesc;
    // End of variables declaration//GEN-END:variables

}
